spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://song-db.cp83phooh2pu.ap-northeast-2.rds.amazonaws.com:3306/armeria
    username: admin
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create
