spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/springtestbyinitializr
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
